name: Review
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  PR_NUMBER: ${{ github.event.number }}
  REPO: ${{ github.repository }}

permissions:
  pull-requests: write

jobs:
  review-check:
    runs-on: ubuntu-latest
    outputs:
      review-result: ${{ steps.review-check-result.outputs.script_result }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Check PR
        id: review-check-result
        run: |
          echo "script_result="$(bash bin/github-review.sh ${PR_NUMBER}) >> $GITHUB_OUTPUT;

  review-output:
    runs-on: ubuntu-latest
    needs: [review-check]
    steps:
    - uses: actions/checkout@v4
    - name: Post Comment to the PR
      if: needs.review-check.outputs.review-result
      run: |
        gh pr comment "$PR_NUMBER" --repo "$REPO" --body ${{ needs.review-check.outputs.review-result }}
